theme = "solarized-dark"
icons = "awesome6"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

#[[block]]
#block = "watson"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 30
format = "%a %d/%m %R"
