theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "watson"

[[block]]
block = "ibus"
[block.mappings]
"mozc-jp" = "JA"
"xkb:us::eng" = "EN"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
