# 2023-03-20: raehik: syntax overhaul and now it's weird and new. not a fan

[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "music"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "

#[[block]]
#block = "watson"

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " SWP $swap_used_percents "

[[block]]
block = "cpu"
interval = 10

[[block]]
block = "load"
interval = 10
#format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 30
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
