# vim: ft=sh
#
# General xinitrc. Tell xinit/startx what programs to start.
#

## Sourcing (inc. specific xinitrcs) {{{
xcfg_dir="$HOME/.config/x"

# load any global config files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# specific xinitrcs
xrdb "$xcfg_dir/Xresources"
source "$xcfg_dir/xinitrc-laptop"
source "$xcfg_dir/graphical-envvars"

# end sourcing: unset variables
#unset xcfg_dir
## }}}

setxkbmap -option compose:menu      # menu = compose key
setxkbmap -option caps:swapescape   # swap caps lock <-> Escape

# turn off all X system bells (PC speaker beeps)
# (note: doesn't affect tty beeps - see your shell rc file (i.e. ~.zshrc))
xset b off

# turn off all mouse acceleration
xset m 1 0

# set desktop background
"$HOME"/.assets/backgrounds/set-desktop-background

## Start-up programs {{{
urxvtd -q -f -o
xinput-keylog &
pasystray &

# start up compositor (for vsync)
# 2016-08-23: seems to be causing some problems with urxvt, so disabled for now
#compton -C -G --no-fading-openclose --vsync opengl &
## }}}

# start keybind daemon
sxhkd &

# start window manager (must be final command!)
exec i3
