#!/usr/bin/env bash
#
# Generate a static MOTD to be placed at /etc/motd.
#

print_cmd="printf"

colour(){
    clr="\e["
    case $1 in
        red) clr="${clr}0;31m" ;;
        red_b) clr="${clr}1;31m" ;;
        green) clr="${clr}0;32m" ;;
        green_b) clr="${clr}1;32m" ;;
        brown) clr="${clr}0;33m" ;;
        brown_b) clr="${clr}1;33m" ;;
        cyan) clr="${clr}0;36m" ;;
        cyan_b) clr="${clr}1;36m" ;;
        blue) clr="${clr}0;34m" ;;
        blue_b) clr="${clr}1;34m" ;;
        reset) clr="${clr}0m" ;;
        *) clr="" ;;
    esac

    $print_cmd "$clr"
}

colour cyan_b
figlet "$(source /etc/os-release; echo "$NAME")"
colour cyan
$print_cmd "Hostname: "
colour green
$print_cmd "$(hostname)\n"
