#!/usr/bin/env bash
#
# #Reload a driver and restart a netctl profile.
# Restart netctl-auto.
#

#driver="rtl8723be"
interface="wlan0"
#current_profile="$(netctl list | grep "^\*" | cut -d ' ' -f 2)"

#sudo modprobe -r "$driver" && sudo modprobe "$driver" && sudo netctl restart "$current_profile"
sudo systemctl restart netctl-auto@"$interface"
