#!/bin/bash
#
# Toggle whether a touchpad is enabled or disabled in X.
#
# Originally shared (and likely written) by ferii on askubuntu.com:
# http://askubuntu.com/a/160549/286269
#
# Heavily edited by raehik.
#

# id can change, so grep for it
id=$(xinput list | grep -Eo 'TouchPad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}')
state=$(xinput list-props $id | grep 'Device Enabled' | awk '{print $4}')

if [ $state -eq 1 ]; then
    xinput disable $id
else
    xinput enable $id
fi
