# vim: ft=sh
#
# bash-specific shell configuration.
#

for f in "$cfg_dir"/bash.d/*; do source "$f"; done

# reset default distro settings
PROMPT_COMMAND=

## Command history {{{
# set history file
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}"/bash_history

# set number of history commands stored in memory
HISTSIZE=1000

# set number of history commands stored in the history file
HISTFILESIZE=2000

# don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
## }}}

# check window size after each command and, if necessary, update $LINES
# and $COLUMNS
shopt -s checkwinsize

# '**' = match all files in *all subdirectories* of all directories
# (i.e. recurse all levels)
shopt -s globstar
