#!/usr/bin/env bash
#
# Common shell configuration (bash + zsh).
#

# set & export XDG info
# not using `user-dirs.dirs` because I don't need `xdg-user-dirs` compatibility
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DESKTOP_DIR="$HOME/.desktop-xdg"
export XDG_DOWNLOAD_DIR="$HOME/tmp/dl"

_cfg_dir="$XDG_CONFIG_HOME/shell"

# shell-specific config
[[ -n "$BASH_VERSION" ]] && source "$_cfg_dir"/bashrc
[[ -n "$ZSH_VERSION"  ]] && source "$_cfg_dir"/zshrc

for f in "$_cfg_dir"/general.d/*; do source "$f"; done
