#!/usr/bin/env bash
#
# Common shell configuration (bash + zsh).
#

# safely get all available XDG directories & set config directory from now on
# straight from freedesktop.org @ https://www.freedesktop.org/wiki/Software/xdg-user-dirs/
test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" \
    && source "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
_cfg_dir="${XDG_CONFIG_HOME:-$HOME/.config}/shell"

# shell-specific config
[[ -n "$BASH_VERSION" ]] && source "$_cfg_dir"/bashrc
[[ -n "$ZSH_VERSION"  ]] && source "$_cfg_dir"/zshrc

for f in "$_cfg_dir"/general.d/*; do source "$f"; done
