#!/usr/bin/env bash
#
# run ssh-agent exactly once for shell session
# (from https://wiki.archlinux.org/index.php/SSH_keys#SSH_agents)
#

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > "$HOME/.cache/ssh-agent-thing"
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<"$HOME/.cache/ssh-agent-thing")"
fi
