# vim: ft=zsh
#
# zsh-specific shell configuration.
#

cache_dir="$HOME/.cache"

# shell theme
_use_conf "zsh-theme"

## Completion-related stuff {{{
# add custom command completions
# note: must be before the autoload -U compinit
fpath=($SHCFG_DIR/zsh-completions $fpath)

# load zsh's great completion features
autoload -U compinit

# run compinit + move zcompdump cache file
compinit -d "$cache_dir/zcompdump"

# alias completions
_use_conf "zsh-completion-aliases"
## }}}

# Vi[m]-style command-line editing
bindkey -v

# Allow comments in interactive mode.
#
#     $ #command to run when I remember syntax
#     $ do this # but not this
#
# You can comment out a line by hitting Alt-#. This inserts a pound sign '#' at
# the start of the line (making the line a comment) and runs the command. To run
# the command for realsies, scroll through your command history and hit Alt-# on
# the commented-out line: it removes the '#' and runs the command!
setopt interactivecomments

## Custom completions {{{
# show a completion menu for commands, files etc. (move around using
# arrow keys)
zstyle ':completion:*:*:*:*:*' menu select

# make zsh's completion use $LS_COLORS
# (stolen from oh-my-zsh)
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# show lots of processes with `kill` completion
# (stolen from oh-my-zsh)
zstyle ':completion:*:*:*:*:processes' command "ps -u `whoami` -o pid,user,comm -w -w"

# & colour `kill` completion
# (stolen from oh-my-zsh)
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
## }}}

## Command history configuration {{{
# file name
HISTFILE="$cache_dir/zsh_history"

# ???
# for setting max no. of commands in history file
HISTSIZE=10000
SAVEHIST=$HISTSIZE

# don't record duplicate lines or lines beginning with a space
# (same as bash HISTCONTROL=ignoreboth)
setopt hist_ignore_dups
setopt hist_ignore_space

# append to history every command
setopt inc_append_history

# actually share the history, between concurrent sessions
setopt share_history

# going up through history scrolls through previous commands starting
# with what you've typed so far
#autoload up-line-or-beginning-search
#autoload down-line-or-beginning-search
#zle -N up-line-or-beginning-search
#zle -N down-line-or-beginning-search
#bindkey "^[[A" up-line-or-beginning-search
#bindkey "^[[B" down-line-or-beginning-search

bindkey '^R' history-incremental-search-backward

# by default, history only outputs the last 16 commands
# wtf that is freaking useless no thx
alias history="history 0"
## }}}

# don't do that dumb query before `rm path/*`
setopt rm_star_silent

# make sure no system-wide files have set 'Ctrl-D doesn't exit' option
unsetopt ignoreeof

# record full command history
_use_conf "zsh-record-full-hist"

# set a custom 'zsh: command not found: $0' message
# args are the command args
#command_not_found_handler() {
#    echo "ayy lmao"
#}
