#!/usr/bin/env bash
#
# Convert all original images to darker & resized background images.
#

# conversion options
## screen width
w=1920

## screen height
h=1080

## image brightness
b=-81

## image contrast
c=-91

bg_dir="bg"

for file in orig/*; do
    filename="${file##*/}"
    ext="${filename##*.}"
    outfile="$bg_dir/${filename%.*}_bg.${ext}"
    echo "$file --> $outfile"
    ./convert-to-bg -w $w -v $h -b $b -c $c "$file" "$outfile"
done
