#!/usr/bin/env bash
engine_current=$(ibus engine)

if [[ "$engine_current" == xkb:gb:*:eng ]]; then
    echo "en_GB"
elif [[ "$engine_current" == "xkb:us:*:eng" ]]; then
    echo "en_US"
elif [[ "$engine_current" == "mozc-jp" ]]; then
    echo "mozc"
else
    echo "IME=?"
fi
