#!/usr/bin/env bash

_prefix_path_if_present "$HOME"/bin "$HOME"/.local/bin

# Rust: cargo package manager
_prefix_path_if_present "$HOME"/.cargo/bin

# Haskell: ghcup
_source_if_present "$HOME"/.ghcup/env

# Go: place in user's local
export GOPATH="$XDG_DATA_HOME"/go
_prefix_path_if_present "$GOPATH"/bin

# Python: set a directory for personal user modules
export PYTHONPATH="$HOME"/.local/share/python-user

# Ruby: rbenv
_eval_if_in_path rbenv init -

# PHP: Composer package manager
_prefix_path_if_present "$HOME"/.config/composer/vendor/bin

# OCaml: opam package manager
_eval_if_in_path opam env

# Homebrew (for Linux)
_eval_if_present "$HOME"/.linuxbrew/bin/brew shellenv

# Rakubrew
_eval_if_present "$HOME"/.rakubrew/bin/rakubrew init Zsh
