#!/usr/bin/env bash

# ls: colors (need to set LS_COLORS, we do dynamically via dircolors)
eval $(dircolors "$_cfg_dir/dircolors")

# man: use nice colours (via exporting termcap values for less)
export LESS_TERMCAP_mb=$'\e[01;31m'
export LESS_TERMCAP_md=$'\e[01;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;44;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'

# turn off all console system bells (PC speaker beeps) - does not affect X
if [[ "$TERM" == "linux" ]]; then
    setterm --blength 0
fi
