#!/usr/bin/env bash
# thanks to Ryan C. Thompson @ https://unix.stackexchange.com/a/149054
_dedup_path_var_perl() {
    path_orig=$(eval echo \$$1)
    path_deduped="$(perl -e 'print join(":",grep { not $seen{$_}++ } split(/:/,
    $ARGV[0]))' "$path_orig")"
    echo "$1"="$path_deduped"
}

eval $(_dedup_path_var_perl PATH)

# I prefer to dedup after the fact. Even if I configure my user-side stuff
# correctly, the host OS might be set up to re-add paths. And it's useful to
# redo user-side stuff if so, to maintain "intended" path order. But this
# function remains since it's a nice proof-of-concept.
#_prefix_path_no_dup() { [[ ":$PATH:" != *":$1:"* ]] && PATH="$1":"$PATH" ; }
