# vim: ft=sh
#
# Main xinitrc that sources others for modularity.
#

xcfg_dir="$HOME/.config/x"

window_manager="i3"

# load any existing global configs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# load specific configs
xrdb "$xcfg_dir/Xresources"
source "$xcfg_dir/xinitrc-base"
source "$xcfg_dir/xinitrc-personal"
source "$xcfg_dir/graphical-envvars"
source "$xcfg_dir/xinitrc-laptop"

# start window manager (must be final command)
exec $window_manager
