#!/usr/bin/env bash
#
# Short description of the program/script's operation/function.
#

# $BLOCK_BUTTON possible values:
#
# ""/[empty]: not clicked
# 1: left click
# 2: middle click
# 3: right click
# 4: scroll up
# 5: scroll down

case $BLOCK_BUTTON in
    1) date "+%Y年%m月%d日" ;;
    *) date "+%H:%M" ;;
esac
