# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.autostart", false);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1406582982);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1406582862);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1406586702);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1406579109);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1406578989);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.dir", "/root/downloads");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/root/downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140722064054");
user_pref("browser.slowStartup.averageTime", 3725);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20140722064054");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.startup.page", 3);
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":0,\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1404065886603");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1406578809814");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1406578811494");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1406665211494");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1404065701951");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1404065840833");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1403540515956");
user_pref("datareporting.sessions.current.activeTicks", 546);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4719);
user_pref("datareporting.sessions.current.main", 1443);
user_pref("datareporting.sessions.current.sessionRestored", 5243);
user_pref("datareporting.sessions.current.startTime", "1406582739088");
user_pref("datareporting.sessions.current.totalTime", 7449);
user_pref("datareporting.sessions.currentIndex", 113);
user_pref("datareporting.sessions.previous.112", "{\"s\":1406578748651,\"a\":62,\"t\":414,\"c\":true,\"m\":12,\"fp\":327,\"sr\":467}");
user_pref("datareporting.sessions.prunedIndex", 111);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"30.0\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"30.0\"}");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("dom.mozApps.used", true);
user_pref("dom.popup_allowed_events", "change click dblclick mouseup reset submit touchend keypress");
user_pref("extensions.blocklist.pingCountTotal", 16);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1406478919000,\"rdfTime\":1406012265000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.liberator.privacy.cpd.commandLine", false);
user_pref("extensions.liberator.privacy.cpd.macros", false);
user_pref("extensions.liberator.privacy.cpd.marks", false);
user_pref("extensions.liberator.saved.accessibility.typeaheadfind", false);
user_pref("extensions.liberator.saved.accessibility.typeaheadfind.autostart", false);
user_pref("extensions.liberator.saved.browser.link.open_newwindow", 3);
user_pref("extensions.liberator.saved.browser.link.open_newwindow.restriction", 0);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.vimperator.firsttime", false);
user_pref("gecko.buildID", "20140722064054");
user_pref("gecko.mstone", "31.0");
user_pref("idle.lastDailyNotification", 1406588436);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1406578810);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1406150071);
user_pref("toolkit.startup.last_success", 1406582740);
user_pref("toolkit.telemetry.previousBuildID", "20140722064054");
